[2025-03-14T15:33:43.146+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T15:33:43.160+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: assignment3.generate_city_report manual__2025-03-14T15:23:33.635212+00:00 map_index=1 [queued]>
[2025-03-14T15:33:43.169+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: assignment3.generate_city_report manual__2025-03-14T15:23:33.635212+00:00 map_index=1 [queued]>
[2025-03-14T15:33:43.169+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-14T15:33:43.175+0000] {taskinstance.py:2890} INFO - Executing <Mapped(_PythonDecoratedOperator): generate_city_report> on 2025-03-14 15:23:33.635212+00:00
[2025-03-14T15:33:43.178+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=744) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T15:33:43.179+0000] {standard_task_runner.py:72} INFO - Started process 745 to run task
[2025-03-14T15:33:43.179+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'assignment3', 'generate_city_report', 'manual__2025-03-14T15:23:33.635212+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/A0265912B.py', '--cfg-path', '/tmp/tmppx8tbyt_', '--map-index', '1']
[2025-03-14T15:33:43.180+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask generate_city_report
[2025-03-14T15:33:43.206+0000] {task_command.py:467} INFO - Running <TaskInstance: assignment3.generate_city_report manual__2025-03-14T15:23:33.635212+00:00 map_index=1 [running]> on host 0b224ca611be
[2025-03-14T15:33:43.242+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='assignment3' AIRFLOW_CTX_TASK_ID='generate_city_report' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T15:23:33.635212+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T15:23:33.635212+00:00'
[2025-03-14T15:33:43.243+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-14T15:33:43.243+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-14T15:33:43.243+0000] {logging_mixin.py:190} INFO - Current task name:generate_city_report state:running start_date:2025-03-14 15:33:43.160704+00:00
[2025-03-14T15:33:43.244+0000] {logging_mixin.py:190} INFO - Dag name:assignment3 and current dag run status:running
[2025-03-14T15:33:43.244+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T15:33:43.245+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/A0265912B.py", line 175, in generate_city_report
    city_data = city_summary[city]
                ~~~~~~~~~~~~^^^^^^
TypeError: unhashable type: 'dict'
[2025-03-14T15:33:43.250+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-14T15:33:43.251+0000] {logging_mixin.py:190} INFO - Task start:2025-03-14 15:33:43.160704+00:00 end:2025-03-14 15:33:43.250232+00:00 duration:0.089528
[2025-03-14T15:33:43.251+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): generate_city_report> dag:<DAG: assignment3> dagrun:<DagRun assignment3 @ 2025-03-14 15:23:33.635212+00:00: manual__2025-03-14T15:23:33.635212+00:00, state:running, queued_at: 2025-03-14 15:23:33.640030+00:00. externally triggered: True>
[2025-03-14T15:33:43.251+0000] {logging_mixin.py:190} INFO - Failure caused by unhashable type: 'dict'
[2025-03-14T15:33:43.251+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=assignment3, task_id=generate_city_report, run_id=manual__2025-03-14T15:23:33.635212+00:00, map_index=1, execution_date=20250314T152333, start_date=20250314T153343, end_date=20250314T153343
[2025-03-14T15:33:43.262+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T15:33:43.262+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 125 for task generate_city_report (unhashable type: 'dict'; 745)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/A0265912B.py", line 175, in generate_city_report
    city_data = city_summary[city]
                ~~~~~~~~~~~~^^^^^^
TypeError: unhashable type: 'dict'
[2025-03-14T15:33:43.278+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-14T15:33:43.285+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T15:33:43.285+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
